typedef enum
{
  FEB_SM_ST_OFF = 0,
  FEB_SM_ST_IDLE,
  FEB_SM_ST_BOOT,
  FEB_SM_ST_LV,
  FEB_SM_ST_HEALTH_CHECK,
  FEB_SM_ST_PRECHARGE,
  FEB_SM_ST_ENERGIZED,
  FEB_SM_ST_DRIVE,
  FEB_SM_ST_FREE,
  FEB_SM_ST_CHARGER_PRECHARGE,
  FEB_SM_ST_CHARGE,
  FEB_SM_ST_CHARGING,
  FEB_SM_ST_BALANCE,
  FEB_SM_ST_FAULT_BMS,
  FEB_SM_ST_FAULT_BSPD,
  FEB_SM_ST_FAULT_IMD,
  FEB_SM_ST_FAULT_CHARGING,
  FEB_SM_ST_DEFAULT
} FEB_SM_ST_t;
