// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: DASH_UI

#include "ui.h"
#include "ui_helpers.h"
#include "lvgl.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
extern lv_obj_t * ui_Screen1;
lv_obj_t * ui_LabelHello;

void ui_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);

    /* Background: Formula Electric Deep Blue */
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x4242FF), 0);
    lv_obj_set_style_bg_opa(ui_Screen1, LV_OPA_COVER, 0);

    /* Create HELLO label */
    ui_LabelHello = lv_label_create(ui_Screen1);
    lv_label_set_text(ui_LabelHello, "FORMULA ELECTRIC");
    
    /* Bold + Large Font */
    lv_obj_set_style_text_font(ui_LabelHello, &lv_font_montserrat_48, 0);
    
    /* Bright Electric Green */
    lv_obj_set_style_text_color(ui_LabelHello, lv_color_hex(0xFFCC12), 0);

    /* Center on Screen */
    lv_obj_center(ui_LabelHello);

    /* Load this screen */
    lv_disp_load_scr(ui_Screen1);

    /* Soft Glow Animation (electric pulse) */
    lv_anim_t pulse;
    lv_anim_init(&pulse);
    lv_anim_set_var(&pulse, ui_LabelHello);
    lv_anim_set_values(&pulse, 180, 255);      // Fade from dim to bright
    lv_anim_set_time(&pulse, 900);             // Pulse speed
    lv_anim_set_repeat_count(&pulse, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_playback_time(&pulse, 900);
    lv_anim_set_exec_cb(&pulse, (lv_anim_exec_xcb_t)lv_obj_set_style_opa);
    lv_anim_start(&pulse);
}


void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
}
